"""added popularSpots

Revision ID: 25668b03d2cf
Revises: f8a2db11f121
Create Date: 2024-08-10 19:47:31.600952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25668b03d2cf'
down_revision = 'f8a2db11f121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poularSpots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_poularSpots_destination_id_destinations')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))

    op.drop_table('poularSpots')
    # ### end Alembic commands ###
