"""renamed some columns

Revision ID: 90655e900106
Revises: 998a19079b79
Create Date: 2024-08-07 23:45:21.426159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90655e900106'
down_revision = '998a19079b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('activity_name', new_column_name='name')
        batch_op.alter_column('activity_description', new_column_name='description')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('destination_description', new_column_name='description')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('itinerary_name', new_column_name='name')
        batch_op.alter_column('itinerary_description', new_column_name='description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('name', new_column_name='itinerary_name')
        batch_op.alter_column('description', new_column_name='itinerary_description')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('description', new_column_name='destination_description')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('name', 'activity_name')
        batch_op.alter_column('description', new_column_name='activity_description')

    # ### end Alembic commands ###
