"""renamed popularSpot table

Revision ID: c551e9c29c4b
Revises: 25668b03d2cf
Create Date: 2024-08-10 20:01:00.225102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c551e9c29c4b'
down_revision = '25668b03d2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('poularSpots', 'popularSpots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('popularSpots', 'poularSpots')
    # ### end Alembic commands ###
